config/routes.rb
Rails.application.routes.draw do
  

  root to: 'registrations#new'
  resource :registrations, only: [:new, :create]
  resource :sessions, only: [:new, :create, :destroy]
  resources :users, only:[:index, :show]

end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  
    validates :name, presence: true, uniqueness: { case_sensitive: false }, format: { with: /\A[a-z][a-z0-9]+\z/ }, length: { in: 4..24 }
    validates :screen_name, length: { maximum: 140 }
    validates :bio, length: { maximum: 200  }
    validates :email, presence: true, uniqueness: { case_sensitive: false }
    validates :password, confirmation: true, length: { in: 6..24 }, if: :password
    validates :password_confirmation, presence: true, if: :password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_url
    else
      render :new
    end
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name,:email,:password,:password_confirmation)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end
  
  def create
    email = user_parasm[:email]
    password = user_params[:password]
    
    if login(email, password)
      redirect_to root_url, notice: "Successfully logged in."
    else
      @user = User.new(email: email)
      render :new
    end
  end
  
  private
  
  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.fetch(:user, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<div class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <%= link_to '#Tsubuyaki', root_url, class: "navbar-brand" %>
    </div>
    <% if logged_in? %>
      <ul class="nav navbar-nav">
        <li>
          <%= link_to "ユーザー一覧", users_path %>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to current_user.name, current_user %>
        </li>
        <li>
          <%= link_to "ログアウト", sessions_path, method: :delete %>
        </li>
      </ul>
    <% else %>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to "会員登録", new_registrations_path %>
        </li>
        <li>
          <%= link_to "ログイン", new_sessions_path %>
        </li>
      </ul>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsTest1</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body id="application">

<div>
<%= render partial: 'layouts/header' %>
<%= yield %>
</div>

</body>
</html>

app/views/layouts/registrations.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
<title>Tsubuyaki22Nov</title>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= csrf_meta_tags %>
</head>
<body id="registrations">
<%= yield %>
</body>
</html>

app/views/layouts/sessions.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
  <title>Tsubuyaki18Oct</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body id="sessions">
  <%= yield %>
</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<div class="col-xs-8" id="users-content">
  <div class="list-group">
    <div class="list-group-item user-list">
      <h2>ユーザー一覧</h2>
    </div>
    <%= div_for @users, class: "list-group-item" do |u| %>
      <h4 class="user">
        <span class="user-name">
          <%= link_to u.name, user_path(u) %>
        </span>
        <span class="user-id">
          @<%= u.name%>
        </span>
      </h4>
      <div class="bio">
        <%= u.bio %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<div class="col-xs-8" id="users-content">
  <div class="user-info">
    <span class="user-name">
      <%= @user.name %>
    </span>
    <span class="user-id">
      @#{@user.name}
    </span>
    <div class="bio">
      <%= @user.bio %>
    </div>
  </div>
</div>